# Generated by Django 4.2 on 2023-04-05 17:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('numero_paginas', models.IntegerField()),
                ('autor', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Livraria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120)),
                ('livros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.livro')),
            ],
        ),
    ]
