# Generated by Django 4.2 on 2023-04-10 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraria',
            name='livros',
        ),
        migrations.AddField(
            model_name='livraria',
            name='livro',
            field=models.ManyToManyField(related_name='livro', to='livro.livro'),
        ),
    ]
