# Generated by Django 4.2 on 2023-04-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_remove_livraria_livros_livraria_livro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livraria',
            name='livro',
        ),
        migrations.AddField(
            model_name='livraria',
            name='livros',
            field=models.ManyToManyField(to='livro.livro'),
        ),
    ]
